### ISSUE TITLE
Maintain perfect repeatability with C implementation

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/DESPOT.jl#10]
As I understand it, all the ccalls to rand_r are for the purpose of being able to exactly reproduce the same results as the C++ implementation. Is that correct?

Do we want to maintain this compatibility? I think maintaining it will make it much more difficult to add functionality.

I think there are 3 options
1. Add features while maintaining compatibility
2. forget compatibility
3. Fork the code and maintain one branch for compatibility and benchmarking and maintain another branch that works with a wider variety of pomdps and options.

What do you think @ebalaban ? I think my vote is for 2 or 3.

**Comment by ebalaban** [comment]
@zsunberg, yes, you are correct about the reason for the ccalls to `rand_r`. My vote would be for option 3.

**Comment by zsunberg** [comment]
Ok - that seems reasonable. Should we make a separate package or keep both branches in this package? And which should be the master branch?

**Comment by ebalaban** [comment]
My preference would be to move the original implementation of DESPOT to another branch and freeze it, aside from bug fixes and such. The modified version would then be in the master branch. I am also not opposed to putting the modified version in a separate package, say DESPOT_M, or something like that.

**Comment by zsunberg** [comment]
Ok, yeah, I think that sounds good. To clarify further: I have been thinking about two classes of features:
1. Modifications to make DESPOT compatible with a wide variety of other POMDPs.jl components (this includes #11 and #12), and
2. Extensions to DESPOT to handle new problems (like continuous observation spaces).
I think the master branch of this package should be broadly compatible with a wide range of POMDPs components, but should only implement the functionality described in the DESPOT paper and not any of our proposed extensions, that is, it should only include features from class 1 above.

If I make any changes to extend DESPOT to continuous observation spaces (class 2 features), I'll start my own repo that depends on this one.

Actually, as I have been modifying the code, it has seemed pretty easy to maintain compatibility with the tests by moving the `rand_r` stuff out into modular optional pieces of code, so perhaps it will not be an issue to maintain compatibility (the one tough thing I have run into is #13). It would be nice to keep the old rock sample tests so that I can ensure that I'm not breaking anything.

**Comment by zsunberg** [comment]
Maybe a good way of deciding what should go in the master branch is to speak in terms of tests. We should decide which RockSample tests we want to pass, and I will submit some tests with other POMDPs.jl problems, and then we can agree on what tests should pass and then talk about what changes need to be made so those tests will pass.

**Comment by ebalaban** [comment]
I think what you are proposing above is a good approach. Let's make sure RockSample tests are passing (and matching the C++ implementation) and if you want to add some more problems to the test set, that's fine.

**Comment by zsunberg** [comment]
Ok, cool. Will submit a PR with some tests shortly. Do the RockSample tests currently in runtests.jl test that we are "matching the C++ implementation"?

**Comment by zsunberg** [comment]
Ok, I put the tests that I think we should shoot to pass in #14 . Let me know what you think. In the lightdark_experiments branch, these tests pass, but unfortunately the RockSample tests do not pass because I wasn't sure how to resolve #13 .

**Comment by ebalaban** [comment]
Ok, great, will take a look a bit later today.

**Comment by zsunberg** [comment]
Minor note: actually I just pushed a small change in the tests that make them not pass on lightdark_experiments because we haven't defined `updater(DESPOTPolicy)`, but I think the updated version contains better tests.

**Comment by zsunberg** [comment]
Ok, I think we have a good way forward with this if we make the tests that were recently merged into master work.
