### ISSUE TITLE
Extra actions in bounds

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/DESPOT.jl#13]
Hi @ebalaban, right now there are some extra actions being passed around between the bounds - specifically the VNode constructor returns an action, and there is an action argument in the lower bound function. Do you think this should be part of the interface (I ask since the README doesn't include this)?

I think that the VNode constructor should only return a VNode, and the lower_bound function should not take an action as an argument.

One way to rectify this would be to get rid of the bounds abstract types - then the upper and lower bounds could be the same object. Then that object could cache actions calculated for the upper bound to be used in the lower bound. I can implement this if it sounds good to you (this is the approach that I have taken for my solver packages, and I have found that it works very well).

**Comment by ebalaban** [comment]
@zsunberg, thanks for the suggestion. Hm, let me see if I understand you correctly. Are you proposing getting rid of bounds abstract types altogether and just having one concrete bound data type (which combines upper and lower bound data)?

My motivation for implementing the bounds interface the way I did it was to allow the user to easily supply custom UB and LB and be able to freely try different implementations. It would seem that what you are proposing would make that harder. I am not necessarily opposed to changing the way actions are passed, but having a single concrete type for UB and LB seems to be limiting. Am I misunderstanding something?

**Comment by zsunberg** [comment]
There would be no abstract types for bounds, so the user could implement separate types for the lower and upper bounds or a single type for both, so it would be more flexible than the current setup.

The reason that I suggest this is because lower_bound currently takes an action argument, and it seems that the reason for this is because the upper and lower bound need to communicate (I am specifically referring to nodes.jl line 122). If both bounds are allowed to be the same object, then the person who writes the bounds type can take care of that if needed, and the lower_bound function does not need the action argument.

**Comment by zsunberg** [comment]
(Or maybe if the upper and lower bounds are always needed at the same time, there should be just one `bounds(bound, pomdp, particles, config)` function that returns a tuple)

**Comment by ebalaban** [comment]
I see. I think I understand what you meant now. Ok, sure, we can get rid of the abstract UB and LB types. I put them in before I started to parametrize all the major types, so they are not all that important now.

**Comment by zsunberg** [comment]
Cool, thanks for removing those. Now we need to get rid of [nodes.jl line 122](https://github.com/JuliaPOMDP/DESPOT.jl/blob/f5f2ace191ac626bda880533a31af3df28bd2ee5/src/nodes.jl#L122) in order to make the usage of the `lower_bound` function match the lower_bound function described in the readme (specifically, it should have only 4 arguments instead of 5).

This will require some changes to the bounds implemented for RockSample. I'm not sure how you want to handle that, but I have some suggestions if you want to hear them.

**Comment by ebalaban** [comment]
Sure. Are you thinking of a single bounds type?

**Comment by zsunberg** [comment]
Yeah, with just one bounds function (assuming the upper and lower bounds
are always needed at the same time).

and if the users want to have separate swappable upper and lower bounds,
they can always make a container for both

**Comment by ebalaban** [comment]
Hm... Well, in the case of RockSample, LB is problem-specific, while UB used is generic (upperBound and lowerBound folders were meant for those). I seem to remember including UB actions as an argument to lower_bound as a temporary workaround - that I then forgot to fix. How about I just add UB action vector as a field in the RockSample POMDP type and that LB (since it is designed to be problem-specific) will just get it from there? This seems to me like a cleaner way of doing it, rather then combining generic and problem-specific code in the same type and function. What do you think?

**Comment by zsunberg** [comment]
I think it would be pretty easy for users to compose bounds for their problem using generic bounds as one of the ingredients... something like

in DESPOT.jl:
```julia
type GenericUpperBound
    #...
end

function upper_bound(u::GenericUpperBound, pomdp::POMDP, ...)
    # just return the upper bound 
end

function upper_bound_and_action(u::GenericUpperBound, pomdp::POMDP, ...)
    # return a tuple of the upper bound and associated action
end
```

in the user's code (or the Rocksample code in this case):
```julia
type ProblemSpecificBounds
    u::GenericUpperBound
    #....
end

function bounds(b::ProblemSpecificBounds, pomdp::POMDP, ...)
     ub, uba = upper_bound_and_action(b.u, pomdp, ...)
     # calculate lower bound lb with uba
     return (lb, ub)
end
```

I'm not sure how the upper bound action thing specific to RockSample worked, so the code above might not exactly cover that case, but something similar should work.

It seems like it would be pretty common for information used to calculate one bound to be useful in calulating another. Having both bounds in the same object would make it easy for users to do that.

**Comment by zsunberg** [comment]
I think putting a UB action vector inside the RockSample problem would be weird because then the solver would be mutating the problem as it calculates those actions (or would they be precalculated?), which seems like an odd link. It seems cleaner to keep the information for the bounds separated from the problem.

**Comment by ebalaban** [comment]
Ok. This method adds more wrappers and more interface code, but I suppose I can live with it. I'll add this to DESPOT and RockSample.

**Comment by ebalaban** [comment]
Implemented with 0e62809 and 29b305c.

**Comment by zsunberg** [comment]
Great, thanks for the fix! Yeah, I think composition (as you have implemented) is the best design pattern to use here. I think a lot of programming authorities (e.g. the book described here https://en.wikipedia.org/wiki/Design_Patterns) promote it, so it is a good idea for us to use it.

One more question:
Can you explain the purpose of the action that needs to be returned by the `bounds` function? Does it correspond to something in the DESPOT paper?

**Comment by zsunberg** [comment]
Hey @ebalaban I'm not sure I understand the action returned by `bounds` (see the question in my post above). It looks like it's just there to set the `root_default_action`. Is that it or am I missing something?

**Comment by ebalaban** [comment]
Yes, it's for setting the default root action with the best LB action of the `VNode`. I could return it through the LB object, then set `best_lb_action` in `VNode` similarly to `best_ub_action`. Then it can be obtained from the root's `VNode` in the solver. A bit more convoluted, but I'd be ok with it if it suits you better.

**Comment by ebalaban** [comment]
Implemented with 9f72a58.

**Comment by zsunberg** [comment]
@ebalaban thanks, I like this a lot better, and I think it will make more sense to other users.

**Comment by zsunberg** [comment]
Tomorrow I think I will merge the other stuff I have written so that the other pomdps tests will work

**Comment by ebalaban** [comment]
Sounds good, thanks @zsunberg.
