### ISSUE TITLE
beliefUpdateParticle in module

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/DESPOT.jl#21]
Should beliefUpdateParticle.jl be included in the module so that it's easier to use? Right now the file has to be included explicitly to be accessed.

Happy to submit a PR if you agree with this, @ebalaban

**Comment by ebalaban** [comment]
I originally kept it separate with the thought of eventually implementing different types of belief updaters. That has not happened yet. Might as well put it in the module for now. If different belief updaters are ever developed, we can move it out (or still keep it there as the default updater). Feel free to submit a PR.

**Comment by zsunberg** [comment]
Ok, will do. There are alternative belief updaters out there, e.g. [ParticleFilters.jl](https://github.com/JuliaPOMDP/ParticleFilters.jl). It might actually be better if one of those was the default, but I will just put beliefUpdateParticle in for now.

**Comment by ebalaban** [comment]
@zsunberg, the build on the PR was failing because MCTS was not being found. I added MCTS to REQUIRE, but that did not solve the problem. Any ideas why this may be happening?

**Comment by zsunberg** [comment]
MCTS is not registered, so putting it in require won't automatically
download it. I'll fix it tomorrow

**Comment by ebalaban** [comment]
Thanks, I thought this might be the case.
